import { useRef, useEffect } from 'react'
import { useAppState } from '../../context/AppStateContext'
import { useHistory } from '../../context/HistoryContext'
import { exportJSON, exportPNG, importJSON } from '../../lib/io'
import { IMAGE_ACCEPT } from '../../lib/images'
import siteIcon from '../../assets/images/site_icon.png'
const tools = [['select','mouse-pointer','Select','V'],['pan','hand','Pan','H'],['rectangle','square','Rectangle','R'],['ellipse','circle','Circle','E'],['arrow','arrow-up-right','Arrow','A'],['line','minus','Line','L'],['pen','pen','Pen','P'],['laser','scan-line','Laser','K'],['text','type','Text','T'],['eraser','eraser','Eraser','X']]
function Icon({ name }) { const common={fill:'none',stroke:'currentColor',strokeWidth:1.9,strokeLinecap:'round',strokeLinejoin:'round'}; const paths={square:<rect x="4" y="4" width="16" height="16" rx="2" {...common}/>,circle:<circle cx="12" cy="12" r="8" {...common}/>,minus:<path d="M4 12h16" {...common}/>,'arrow-up-right':<><path d="M5 19 19 5M8 5h11v11" {...common}/></>,type:<><path d="M4 6V4h16v2M12 4v16M8 20h8" {...common}/></>,eraser:<path d="m7 19-3-3a2 2 0 0 1 0-3l7-7a2 2 0 0 1 3 0l5 5a2 2 0 0 1 0 3l-5 5H7Z" {...common}/>,pen:<><path d="m4 20 4-1 10-10-3-3L5 16l-1 4Z" {...common}/><path d="m13 8 3 3" {...common}/></>,'scan-line':<><path d="M4 7V5h2M18 5h2v2M20 17v2h-2M6 19H4v-2M5 12h14" {...common}/></>,'mouse-pointer':<path d="m5 3 6 17 2-7 7-2L5 3Z" {...common}/>,hand:<><path d="M8 11V5a1.5 1.5 0 0 1 3 0v5V3.5a1.5 1.5 0 0 1 3 0V10V5a1.5 1.5 0 0 1 3 0v6" {...common}/><path d="M8 9.5 6.8 8.3a1.5 1.5 0 0 0-2.1 2.1l4.4 6a4 4 0 0 0 3.2 1.6h2.2a4 4 0 0 0 4-4V11" {...common}/></>,undo:<path d="M9 7 4 12l5 5M4 12h10a5 5 0 0 1 5 5" {...common}/>,redo:<path d="m15 7 5 5-5 5M20 12H10a5 5 0 0 0-5 5" {...common}/>,download:<><path d="M12 3v12M7 10l5 5 5-5M5 21h14" {...common}/></>,upload:<><path d="M12 15V3M7 8l5-5 5 5M5 21h14" {...common}/></>,image:<><rect x="3" y="4" width="18" height="16" rx="2" {...common}/><circle cx="8" cy="9" r="1" {...common}/><path d="m21 15-5-5L5 20" {...common}/></>};return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg> }
export default function Toolbar({ stageRef, onImageUpload }) { const {state,dispatch}=useAppState(); const {shapes,commit,undo,redo,revision}=useHistory(); const input=useRef(); const imageInput=useRef(); const fileNameInput=useRef(); const revisionRef=useRef(revision); const importToken=useRef(0); useEffect(()=>{revisionRef.current=revision},[revision]); useEffect(()=>{document.title=state.fileName+' - Diagram board'},[state.fileName]); const load=async e=>{const token=++importToken.current;const baseRevision=revisionRef.current;const file=e.target.files?.[0];try{const imported=await importJSON(file);if(token!==importToken.current)return;if(revisionRef.current!==baseRevision){alert('The board changed while the file was loading. Import was cancelled to protect your edits.');return}commit(imported)}catch(error){if(token===importToken.current)alert(error.message)}finally{e.target.value=''}}; const loadImage=async e=>{try{const file=e.target.files?.[0];if(file)await onImageUpload(file)}catch(error){alert(error.message)} e.target.value=''}; const button=(name,title,onClick)=><button title={title} aria-label={title} onClick={onClick}><Icon name={name}/></button>; const toolButtons=items=>items.map(([tool,icon,name,key])=><button key={tool} className={state.activeTool===tool?'active':''} title={`${name} (${key})`} onClick={()=>dispatch({type:'SET_TOOL',tool})}><Icon name={icon}/></button>); const commitName=()=>{const v=fileNameInput.current.value.trim();if(v&&v!==state.fileName){dispatch({type:'SET_FILENAME',fileName:v})}else{fileNameInput.current.value=state.fileName}}; return <><nav className="left-toolbar" aria-label="Drawing tools">{toolButtons(tools.slice(0,2))}<span className="tool-divider"/>{toolButtons(tools.slice(2,6))}<span className="tool-divider"/>{toolButtons(tools.slice(6))}<span className="tool-divider"/><button title="Insert image" aria-label="Insert image" onClick={()=>imageInput.current.click()}><Icon name="image"/></button><input ref={imageInput} type="file" accept={IMAGE_ACCEPT} hidden onChange={loadImage}/></nav><nav className="top-toolbar" aria-label="Document actions"><span className="board-label"><img className="board-mark" src={siteIcon} alt=""/><input ref={fileNameInput} className="board-name-input" type="text" defaultValue={state.fileName} onBlur={commitName} onKeyDown={e=>{if(e.key==='Enter')e.target.blur()}}/></span><span className="divider"/>{button('undo','Undo (Ctrl+Z)',undo)}{button('redo','Redo (Ctrl+Shift+Z)',redo)}<span className="divider"/>{button('upload','Import diagram',()=>input.current.click())}{button('download','Export JSON',()=>exportJSON(shapes,state.fileName))}{button('image','Export PNG',()=>exportPNG(stageRef.current,state.fileName))}<input ref={input} type="file" accept="application/json" hidden onChange={load}/></nav></> }
