import { useCallback, useEffect, useRef, useState } from 'react'
import { AppStateProvider, useAppState } from './context/AppStateContext'
import { HistoryProvider, useHistory } from './context/HistoryContext'
import CanvasStage from './components/Canvas/CanvasStage'
import Toolbar from './components/Toolbar/Toolbar'
import StylePanel from './components/StylePanel/StylePanel'
import ZoomControls from './components/ZoomControls/ZoomControls'
import SplashScreen from './components/SplashScreen/SplashScreen'
import { useKeyboardShortcuts } from './hooks/useKeyboardShortcuts'
import { newId } from './lib/idGenerator'
function Workspace({ onReady }){const stageRef=useRef(); const [view,setView]=useState({x:0,y:0,scale:1}); const {state,dispatch}=useAppState();const {shapes,commit,undo,redo}=useHistory();const remove=useCallback(()=>{if(state.selectedShapeIds.length){commit(shapes.filter(s=>!state.selectedShapeIds.includes(s.id)));dispatch({type:'SET_SELECTION',ids:[]})}},[shapes,state.selectedShapeIds,commit,dispatch]);const nudge=useCallback((dx,dy)=>{if(!state.selectedShapeIds.length)return;const set=new Set(state.selectedShapeIds);commit(shapes.map(s=>set.has(s.id)?{...s,x:Math.round(s.x+dx),y:Math.round(s.y+dy)}:s))},[shapes,state.selectedShapeIds,commit]);const duplicate=useCallback(()=>{if(!state.selectedShapeIds.length)return;const set=new Set(state.selectedShapeIds);const copies=shapes.filter(s=>set.has(s.id)).map(s=>({...s,id:newId(),x:s.x+20,y:s.y+20}));commit([...shapes,...copies]);dispatch({type:'SET_SELECTION',ids:copies.map(s=>s.id)})},[shapes,state.selectedShapeIds,commit,dispatch]);const selectAll=useCallback(()=>dispatch({type:'SET_SELECTION',ids:shapes.map(s=>s.id)}),[shapes,dispatch]);const deselect=useCallback(()=>dispatch({type:'SET_SELECTION',ids:[]}),[dispatch]);useKeyboardShortcuts({dispatch,undo,redo,remove,nudge,duplicate,selectAll,deselect});useEffect(()=>{const frame=requestAnimationFrame(onReady);return()=>cancelAnimationFrame(frame)},[onReady]);return <main><CanvasStage stageRef={stageRef} view={view} setView={setView}/><Toolbar stageRef={stageRef}/><StylePanel/><ZoomControls view={view} setView={setView}/></main>}
export default function App(){const [splash,setSplash]=useState('visible');const startedAt=useRef(performance.now());const dismiss=useCallback(()=>{const wait=Math.max(0,6500-(performance.now()-startedAt.current));window.setTimeout(()=>setSplash('leaving'),wait)},[]);return <AppStateProvider><HistoryProvider><Workspace onReady={dismiss}/>{splash!=='done'&&<SplashScreen leaving={splash==='leaving'} onHidden={()=>setSplash('done')}/>}</HistoryProvider></AppStateProvider>}
